meta_product_name: "Sunsetter"
meta_title: "Sunsetter - Share The Moment"
meta_description: "The sun sets once in a day - make the most of the moment."
meta_image: "https://res.cloudinary.com/dguxqdu8p/image/upload/v1575538826/ogimage_ferivj.jpg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
